---
spring:
  profiles: default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/claudioed/album-files
  application:
    name: configserver

logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG

server:
  port: 8001